### ISSUE TITLE
Elasticsearch is still initializing the kibana index

### ISSUE THREAD

**Issue by xmlx** [dtag-dev-sec/tpotce#212]
# Contribution

Thank you for your decision to contribute to T-Pot.

## Issues

Please feel free to post your problems, ideas and issues [here](https://github.com/dtag-dev-sec/tpotce/issues). We will try to answer ASAP, but to speed things up we encourage you to ...
- [ ] Use the [search function](https://github.com/dtag-dev-sec/tpotce/issues?utf8=%E2%9C%93&q=) first
- [ ] Check the [FAQ](#faq)
- [ ] Provide [basic support information](#info) with regard to your issue

Thank you :smiley:

-

<a name="faq"></a>
###### The honeypot logs are located in `/data/`. You have to login via ssh and run `sudo cd /data/`. Do not change any permissions here or T-Pot will fail to work.

-

<a name="info"></a>
### Baisc support information

- What T-Pot version are you currtently using?17.10
- Are you running on a Intel NUC or a VM? vm
- How long has your installation been running? 5 months
- Did you install any upgrades or packages?no
- Did you modify any scripts?no
- Have you turned persistence on/off?no
- How much RAM available (login via ssh and run `htop`)?
- How much stress are the CPUs under (login via ssh and run `htop`)?
- How much swap space is being used (login via ssh and run `htop`)?
- How much free disk space is available (login via ssh and run `sudo df -h`)?
- What is the current container status (login via ssh and run `sudo start.sh`)?

Hi, 
I'm getting this error as mentioned in title, but never get the web interface back up and running normally again. Anything i can do to fix this issue?

**Comment by t3chn0m4g3** [comment]
Is `Head` available at the web GUI?

**Comment by xmlx** [comment]
ES Head:
cluster health: not connected

**Comment by t3chn0m4g3** [comment]
Please ...

```
sudo su -
systemctl stop tpot
vi /opt/tpot/etc/tpot.yml
```

... and give elasticsearch more RAM (see example below), then `reboot`:

```
# ELK services
## Elasticsearch service
  elasticsearch:
    container_name: elasticsearch
    restart: always
    environment:
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    cap_add:
     - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    ports:
     - "127.0.0.1:64298:9200"
    image: "dtagdevsec/elasticsearch:1804"
    volumes:
     - /data:/data
```

After reboot log in again and ...
```
sudo su -
docker logs elasticsearch --follow
```

... wait some time and monitor the output.

Also check via `htop` and `glances` if your system started swapping.
