### ISSUE TITLE
Making changes to the logstash docker container stick between reboots/restarts

### ISSUE THREAD

**Issue by LandonStewart** [dtag-dev-sec/tpotce#254]
I've successfully made logstash send the tpot data to our own elasticsearch instance and imported all the necessary searches/visualations/dashboards/etc into our Kibana but when the tpot service is restarted the logstash docker container reverts it's `/etc/logstash/conf.d/logstash.yml` back to it's original version.

Here's what I'm doing:

- Login to the t-pot host `ssh -p 64295 tsec@<ipaddr>`
- Find the container ID for logstash (ie. `docker container list | grep logstash`)
- Enter the logstash container (ie. `docker exec -it 5e14163b7673 bash`)
- Edit the file `/etc/logstash/conf.d/logstash.conf` to direct elasticsearch output to our elasticsearch
- Leave the container
- Make the same edit in `/opt/tpot/docker/elk/logstash/dist/logstash.conf` on the host.
- Restart the logstash container (ie. `docker restart 5e14163b7673`)
- Change to `/opt/tpot/bin` and run `./export_kibana-objects.sh`.  This will produce a file like `kibana-objects_201810252016.tgz`.
- Temporarily edit or copy and edit the file `import_kibana-objects.sh` and change the line `myES="http://127.0.0.1:64298/"` to our elasticsearch.
- Execute the import script (or the copy you edited) with the filename of the export (ie. `./import_kibana-objects.sh kibana-objects_201810252016.tgz`)
- Ensure logstash has completed starting up (run `dps.sh` from any directory on the host).  The logstash container should say (healthy) instead of (starting).
- Check out our Kibana.

When `tpot` is restarted however the logstash docker container reverts to `hosts => ["elasticsearch:9200"]`.  How can I make this setting stick between reboots/restarts of the logstash docker container?  I've tried making the same edit to the file `/opt/tpot/docker/elk/logstash/dist/logstash.conf` but this file does not get used when the docker container is restarted (rebuilt?).

**Comment by LandonStewart** [comment]
Nevermind...  I've mapped the file `/opt/tpot/docker/elk/logstash/dist/logstash.conf` after modifying it to `/etc/logstash/conf.d/logstash.conf` in the docker container by editing `/opt/tpot/etc/tpot.yml` and adding the last line in the following section pasted below:

```
  logstash:
    container_name: logstash
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
     - /opt/tpot/etc/compose/elk_environment
    image: "dtagdevsec/logstash:1710"
    volumes:
     - /data:/data
     - /var/log:/data/host/log
     - /opt/tpot/docker/elk/logstash/dist/logstash.conf:/etc/logstash/conf.d/logstash.conf
```

When tpot is restarted the `/etc/logstash/conf.d/logstash.conf` within the container has the right setting for elasticsearch's host and port.
