### ISSUE TITLE
Changing cowrie.cfg in cowrie container reverts my changes after a while

### ISSUE THREAD

**Issue by micoots** [dtag-dev-sec/tpotce#260]
What T-Pot version are you currtently using? 17.10
Are you running on a Intel NUC or a VM? VM
How long has your installation been running? About 1 week
Did you install any upgrades or packages? no
Did you modify any scripts? no
Have you turned persistence on/off? no
How much RAM available (login via ssh and run htop)? 3.80G available, 2.46G used
How much stress are the CPUs under (login via ssh and run htop)? little, load avergae 0.34,0.32,0.29
How much swap space is being used (login via ssh and run htop)? 0K out of 8GB
How much free disk space is available (login via ssh and run sudo df -h)? 40GB available
What is the current container status (login via ssh and run sudo start.sh)?
Using WebTTY, start.sh command not found.
Using Portainer, all containers are up.

Goal:

I am trying to modify the cowrie.cfg file to also allow me to report to DShield and others.

Problem:

When I go into Portainer, access cowrie, then console, I modify cowrie.cfg to add my API items into the setup.

I then "reboot" the container, or restart it, and the items are loaded.

When I check back the next day, I find any changes I made are gone and the cowrie.cfg is back to default.

How can I make my changes persistent so I can use some of this data to contribute to other projects like DShield, instead of just https://sicherheitstacho.eu/start/main.

Thank you.

**Comment by LandonStewart** [comment]
AFAIK you have to modify a file outside the container and then map that file to take precedence over the file within the container.

I would edit this:
/opt/tpot/docker/cowrie/dist/cowrie.cfg

Then map it to a file within the container by editing the volumes in the cowrie section of /opt/tpot/etc/tpot.yml.

Something like (notice the last line):

```
# Cowrie service
  cowrie:
    container_name: cowrie
    restart: always
    networks:
     - cowrie_local
    cap_add:
     - NET_BIND_SERVICE
    ports:
     - "22:2222"
     - "23:2223"
    image: "dtagdevsec/cowrie:1710"
    volumes:
     - /data/cowrie/downloads:/home/cowrie/cowrie/dl
     - /data/cowrie/keys:/home/cowrie/cowrie/etc
     - /data/cowrie/log:/home/cowrie/cowrie/log
     - /data/cowrie/log/tty:/home/cowrie/cowrie/log/tty
     - /opt/tpot/docker/cowrie/dist/cowrie.cfg:/home/cowrie/cowrie/cowrie.cfg
```

I haven't tried this but this is what I would try.
