### ISSUE TITLE
Filebeat Hurdaling config 

### ISSUE THREAD

**Issue by iukea1** [dtag-dev-sec/tpotce#376]
Hey, guys, I am having an issue with my Filebeat yml config and was curious if any of you could spot anything obvious that I missing? 

Just trying to send logs back to my centeral tpot/elk server. 

```
# Heralding
     -
        paths:
        - /data/heralding/log/auth.csv"
        input_type: log
        document_type: Heralding
        fields:
        fields_under_root: true





output.logstash:
   hosts:
      - 'my ip and this is the correct port for me:6990'
logging.level: debug
logging.selectors:
    - publish
```
