### ISSUE TITLE
📢 Attention NextGen 19.03.x users - Journey towards T-Pot 20.06 📢

### ISSUE THREAD

**Issue by t3chn0m4g3** [dtag-dev-sec/tpotce#531]
We started the rollout of ELK 7.x into NextGen 19.03.x. The images will not be enabled automatically, to do so just run the `/opt/tpot/update.sh` as root (`sudo su -`).

### Limitations
- Once on ELK 7.x within NextGen you should not switch editions with `tped.sh` any more. It will result in data loss, remains untested and will be unsupported. Please backup your data or machine before running the `update.sh` script.

### Known Issues
- Dark mode needs to be re-enabled manually. To do so, go to `Kibana > Management > Advanced Settings > Dark Mode` and enable it.
- In some occasions you will receive the error `shards failed` containing the error message `elasticsearch field expansion matches too many fields, limit: 1024, got: XYZ` - or no data at all. The reason for this lies within some changes of the Elastic Stack. To resolve this, just update existing indices by opening the Kibana Dev console and put the following settings to the indices:
```
PUT /logstash-*/_settings
{
  "index.query": {
      "default_field": "fields.*"
  }
}
```
![image](https://user-images.githubusercontent.com/4318452/73648577-28a5ce80-467e-11ea-9363-841ec3a49605.png)

If everything worked you will receive `{ "acknowledged" : true }` and can check if all the indices have been updated with `GET /logstash-*/_settings`, which should look like this:
```
{
  "logstash-2019.12.05" : {
    "settings" : {
      "index" : {
        "mapping" : {
          "total_fields" : {
            "limit" : "2000"
          }
        },
        "refresh_interval" : "5s",
        "number_of_shards" : "1",
        "provided_name" : "logstash-2019.12.05",
        "query" : {
          "default_field" : "fields.*"
        },
        "creation_date" : "1575575581123",
        "number_of_replicas" : "0",
        "uuid" : "KlTv3hpCSly0UTzTmpVV7g",
        "version" : {
          "created" : "6080299",
          "upgraded" : "7050299"
        }
      }
    }
  },
  "logstash-2019.12.10" : {
    "settings" : {
      "index" : {
        "mapping" : {
          "total_fields" : {
            "limit" : "2000"
          }
        },
        "refresh_interval" : "5s",
        "number_of_shards" : "1",
        "provided_name" : "logstash-2019.12.10",
        "query" : {
          "default_field" : "fields.*"
        },
        "creation_date" : "1575936000623",
        "number_of_replicas" : "0",
        "uuid" : "OOtnisiBTkiI-MDVJITUwA",
        "version" : {
          "created" : "6080299",
          "upgraded" : "7050299"
        }
      }
    }
  },
[...]
```

- Elasticsearch will be needing at least 2GB of RAM reserved, larger installations should opt for 4GB of RAM. Modify `/opt/tpot/etc/tpot.yml` settings for `elasticsearch` accordingly, it needs more RAM:

```
#### ELK
## Elasticsearch service
  elasticsearch:
    container_name: elasticsearch
    restart: always
    environment:
     - bootstrap.memory_lock=true
     - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
     - ES_TMPDIR=/tmp
    cap_add:
     - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    ports:
     - "127.0.0.1:64298:9200"
    image: "dtagdevsec/elasticsearch:2006"
    volumes:
     - /data:/data
```

- Should you have troubles with your objects, please find attached the latest Kibana objects, just extract them and import the `ndjson` via `Management > Kibana > Saved Objects > Import` (be aware of overwriting, though!):

[export.zip](https://github.com/dtag-dev-sec/tpotce/files/4160171/export.zip)

Once ELK 7.x will be T-Pot's default, new installations will not be affected by these issues.

![image](https://user-images.githubusercontent.com/4318452/73556321-830d1800-444f-11ea-8871-e640d658c365.png)

**Comment by jrsanchezsilva** [comment]
Good Morning. Given the need to update Kibana. I have some doubts that I ask please can answer.

1. I see that there are some problems regarding the objects that you comment. I ask this because I have already implemented the Kibana with version 6.8.6 on my server and it works perfectly. So I have a little concern with the problems that may arise on my server with ELK 7.x

2. I was reading some options to get a pdf report in Kibana. My question is whether in this new version of Kibana, the report is already available by default or some recommendations you may have to implement the report option in Kibana 6.8.6

Thank you

Best regards

**Comment by t3chn0m4g3** [comment]
@jrsanchezsilva 
1. If you are concerned you should not update.
2. This is a licensing issue regarding XPack, please check with Elastic.

**Comment by jrsanchezsilva** [comment]
Good Morning. I installed the latest version in a virtual machine to verify the changes. However, I have problems with the dockers that are up a few seconds and then down. I went to check the Kibana, I found the new items on the home screen. However, the Kibana never entered. Thank you. Best regards.

**Comment by t3chn0m4g3** [comment]
@jrsanchezsilva This seems unrelated, please open a new issue and provide basic support info.

**Comment by Patrik-Hansson** [comment]
Tried to enable dark mode, when klicking save i get:

Unable to update UI setting
Failed to fetch
Anything you have seen? Shall i create an issue for it ?

**Comment by t3chn0m4g3** [comment]
Modify `/opt/tpot/etc/tpot.yml` settings for `elasticsearch` accordingly, it needs more RAM:
```
#### ELK
## Elasticsearch service
  elasticsearch:
    container_name: elasticsearch
    restart: always
    environment:
     - bootstrap.memory_lock=true
     - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
     - ES_TMPDIR=/tmp
    cap_add:
     - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    ports:
     - "127.0.0.1:64298:9200"
    image: "dtagdevsec/elasticsearch:2006"
    volumes:
     - /data:/data
```
