### ISSUE TITLE
Modify the user "admin" in KIBANA

### ISSUE THREAD

**Issue by jrsanchezsilva** [dtag-dev-sec/tpotce#534]
Good evening, how can I modify the user "admin" when trying to modify the windows in kibana; since at the time of installation I only add the password of the user tsec and the user to log in from his browser but no time the user admin; As shown in the window, thank you very much in advance.

![image](https://user-images.githubusercontent.com/51901933/73803856-fedccc80-478f-11ea-86b2-239cf750d27c.png)

Every time I want to modify this user I get this error
![image](https://user-images.githubusercontent.com/51901933/73804661-7e6b9b00-4792-11ea-9301-49442f24ba53.png)

**Comment by t3chn0m4g3** [comment]
This is by design, since the container is started as read-only. Enabling user management will not improve security of the provided services. However you can adjust `/opt/tpot/etc/tpot.yml` to start the container with a persistent cache. Once enabled the cache will be preferred over any changes within the application and thus will not provide updates present in the image.

Follow this example to enable the cache in `tpot.yml` ...

```
# Nginx service
  nginx:
    container_name: nginx
    restart: always
    environment:
    ### If set to YES all changes within Heimdall will remain for the next start
    ### Make sure to uncomment the corresponding volume statements below, or the setting will prevent a successful start of T-Pot.
     - HEIMDALL_PERSIST=YES
    tmpfs:
     - /var/tmp/nginx/client_body
     - /var/tmp/nginx/proxy
     - /var/tmp/nginx/fastcgi
     - /var/tmp/nginx/uwsgi
     - /var/tmp/nginx/scgi 
     - /run
     - /var/log/php7/
     - /var/lib/nginx/tmp:uid=100,gid=82 
     - /var/lib/nginx/html/storage/logs:uid=100,gid=82
     - /var/lib/nginx/html/storage/framework/views:uid=100,gid=82
    network_mode: "host"
    ports:
     - "64297:64297"
     - "127.0.0.1:64304:64304"
    image: "dtagdevsec/nginx:2006"
    read_only: true
    volumes:
     - /data/nginx/cert/:/etc/nginx/cert/:ro
     - /data/nginx/conf/nginxpasswd:/etc/nginx/nginxpasswd:ro
     - /data/nginx/log/:/var/log/nginx/
    ### Enable the following volumes if you set HEIMDALL_PERSIST=YES
    - /data/nginx/heimdall/database:/var/lib/nginx/html/database
    - /data/nginx/heimdall/storage:/var/lib/nginx/html/storage
```
