### ISSUE TITLE
Cloned website whit Snare

### ISSUE THREAD

**Issue by sarebour** [dtag-dev-sec/tpotce#642]
Hello,
I just copied my own website whit Snare and copied the pages into a custom mount as said here:
https://github.com/dtag-dev-sec/tpotce/issues/264#issuecomment-442371153

after that I used the same CMD in the Snare Dockerfile whitout the randomization string into tpot.yml but when the honeypot comes up, I see the html code (not rendered). Should I modify something else?

Thanks!

**Comment by pisces-period** [comment]
Hi @sarebour,

Could you please share your custom Dockerfile and t-pot.yml file, if you are using it?

And also, what OS is your docker running on? Windows, Mac or Linux? A little bit more of information would help to figure out what might be happening.

By default, DT-AG's Snare Dockerfile copies a set of random pages to _/opt/snare/pages_ (snare's default page-dir) and then invokes _CMD_ to randomly choose one every time you start a new container. 

You need to override both the contents of _/opt/snare/pages_ and the _CMD_ command to point to your pages instead.

Fortunately, you can achieve both by editing the 'snare' section of the docker-compose file. For example:
```
## Snare Service
  snare:
    container_name: snare
    restart: always
    tty: true
    command: snare --tanner tanner --debug true --no-dorks true --auto-update false --host-ip 0.0.0.0 --port 80 --page-dir ${my_page_dir}
    networks:
     - tanner_local
    ports:
     - "80:80"
    image: "dtagdevsec/snare:1903"
    depends_on:
     - tanner
    volumes:
    - ${/path/to/your/mount}:/opt/snare/pages
```
Where:
- `${/path/to/your/mount}`: absolute path of your mount (i.e., the directory where the pages directory reside on your host) 
- `${my_page_dir}`: your pages directory, relative path to "/opt/snare/pages"

IIRC the t-pot.yml file is dynamically created based on what flavor you pick when you install it, so you might end up needing to edit the docker-compose file in _tpotce/etc/compose_ that corresponds to whatever flavor you plan to use.
